#%RAML 1.0 Library
types:
  Property:
    type: object
    properties:
      key:   string
      value: string
  Field:
    type: object
    properties:
      type: string
      name: string
      optional:
        type: boolean
        default: true
  Schema:
    type: object
    properties:
      version:       string
      name:          string
      dateModified:  datetime
      documentation: string
      fields:        Field[]
  Cluster:
    type: object
    properties:
      name: string
      kafka.metadata.broker.list: string
      kafka.zookeeper.quorum: string
      kafka.topic.autoCreate:
        type: boolean
        default: true
      kafka.topic.default.partitions:
        type: number
        minimum: 1
      kafka.topic.default.replicationFactor:
        type: number
        minimum: 1
  Topic:
    type: object
    properties:
      name: string
      serializer: string
      schema: Schema
  Job:
    type: object
    properties:
      version:       string
      name:          string
      dateModified:  datetime
      documentation: string
      streams:       Stream[]
  Stream:
    type: object
    properties:
      name:          string
      component:     string
      documentation: string
      kafka.input.topics: Topic[]
      kafka.output.topics: Topic[]
      kafka.error.topics: Topic[]
      processors: Processor[]
  Processor:
    type: object
    properties:
      name:          string
      component:     string
      documentation: string
      config:        Property[]
